# sql_rag.py
"""SQL RAG chain for analytical queries.

- Uses an LLM (OpenAI) to translate a natural‑language question into a SQL statement.
- Extracts the raw SQL (removing markdown fences or explanatory text).
- Executes the SQL against the supplied SQLite database (`mediassist.db`).
- Returns the query result as JSON and feeds it back to the LLM for a natural‑language answer.

Only roles `billing_executive` and `admin` are allowed to invoke this function.
"""

import os
import re
import json
import sqlite3
from typing import List, Dict, Any
from dotenv import load_dotenv
load_dotenv()


# ChatGroq LLM integration
try:
    from langchain_groq import ChatGroq
    from langchain_core.messages import SystemMessage, HumanMessage
except ImportError as e:
    raise ImportError("Please install langchain-groq: pip install langchain-groq")

# Initialize ChatGroq
GROQ_MODEL = "openai/gpt-oss-20b"
llm = ChatGroq(
    temperature=0,
    model_name=GROQ_MODEL,
    api_key=os.getenv("LLM_API_KEY") or os.getenv("GROQ_API_KEY")
)

def _call_llm(prompt: str) -> str:
    """Wrap Groq ChatCompletion call using LangChain.
    Returns the raw assistant content.
    """
    messages = [
        SystemMessage(content="You translate a natural‑language question into a valid SQLite query. Return only the SQL, without any explanation or markdown fences."),
        HumanMessage(content=prompt)
    ]
    response = llm.invoke(messages)
    return response.content.strip()

def _extract_sql(raw: str) -> str:
    """Strip markdown fences and surrounding text, leaving just the SQL statement."""
    # Remove triple backticks and optional language identifier
    cleaned = re.sub(r"^```\w*\n?|\n?```$", "", raw, flags=re.MULTILINE).strip()
    return cleaned

def sql_rag_chain(question: str, role: str) -> str:
    """Full SQL‑RAG pipeline.

    Args:
        question: Natural‑language analytical question.
        role: Authenticated user role (must be 'billing_executive' or 'admin').
    Returns:
        A human‑readable answer generated by the LLM.
    """
    if role not in {"billing_executive", "admin"}:
        raise PermissionError(f"Role '{role}' is not permitted to run SQL RAG.")

    # 1️⃣ Convert question to SQL via LLM
    llm_prompt = f"Translate the following question into a single SQLite query.\nQuestion: {question}\nSQL:"
    raw_sql = _call_llm(llm_prompt)
    sql = _extract_sql(raw_sql)

    # 2️⃣ Execute the SQL safely
    db_path = os.path.join(os.path.dirname(__file__), "data", "db", "mediassist.db")
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    try:
        cur = conn.execute(sql)
        rows = cur.fetchall()
        # Convert rows to list of dicts for easy JSON handling
        results: List[Dict[str, Any]] = [dict(row) for row in rows]
    finally:
        conn.close()

    # 3️⃣ Feed result back to LLM for a natural answer
    results_json = json.dumps(results, indent=2, ensure_ascii=False)
    answer_prompt = (
        f"Given the original question:\n{question}\nAnd the SQL result (JSON):\n{results_json}\nProduce a concise natural‑language answer."
    )
    answer = _call_llm(answer_prompt)
    return answer

if __name__ == "__main__":
    # Demo – replace with real credentials / role
    #  demo_q = "which medical equipment models break down the most frequently and group them by fault codes."
    demo_q = "calculates the total money claimed versus approved."
    # demo_q = "which diagnosis codes or claim types trigger the most frequent claim rejections by insurance companies?"
    demo_role = "billing_executive"
    print(sql_rag_chain(demo_q, demo_role))
