# sql_rag.py
"""SQL RAG chain for analytical queries.

- Uses an LLM (OpenAI) to translate a natural‑language question into a SQL statement.
- Extracts the raw SQL (removing markdown fences or explanatory text).
- Executes the SQL against the supplied SQLite database (`mediassist.db`).
- Returns the query result as JSON and feeds it back to the LLM for a natural‑language answer.

Only roles `billing_executive` and `admin` are allowed to invoke this function.
"""

import os
import re
import json
import sqlite3
from typing import List, Dict, Any

# LLM client – placeholder; replace with your actual provider (OpenAI, Anthropic, etc.)
try:
    import openai
except ImportError as e:
    raise ImportError("Please install the OpenAI SDK in the virtual environment (pip install openai).")

# Model name can be overridden via env var
OPENAI_MODEL = os.getenv("OPENAI_MODEL", "gpt-4o-mini")

def _call_llm(prompt: str) -> str:
    """Wrap OpenAI ChatCompletion call.
    Returns the raw assistant content.
    """
    response = openai.ChatCompletion.create(
        model=OPENAI_MODEL,
        messages=[
            {"role": "system", "content": "You translate a natural‑language question into a valid SQLite query. Return only the SQL, without any explanation or markdown fences."},
            {"role": "user", "content": prompt},
        ],
        temperature=0,
    )
    return response.choices[0].message.content.strip()

def _extract_sql(raw: str) -> str:
    """Strip markdown fences and surrounding text, leaving just the SQL statement."""
    # Remove triple backticks and optional language identifier
    cleaned = re.sub(r"^```\w*\n?|\n?```$", "", raw, flags=re.MULTILINE).strip()
    return cleaned

def sql_rag_chain(question: str, role: str) -> str:
    """Full SQL‑RAG pipeline.

    Args:
        question: Natural‑language analytical question.
        role: Authenticated user role (must be 'billing_executive' or 'admin').
    Returns:
        A human‑readable answer generated by the LLM.
    """
    if role not in {"billing_executive", "admin"}:
        raise PermissionError(f"Role '{role}' is not permitted to run SQL RAG.")

    # 1️⃣ Convert question to SQL via LLM
    llm_prompt = f"Translate the following question into a single SQLite query.\nQuestion: {question}\nSQL:"
    raw_sql = _call_llm(llm_prompt)
    sql = _extract_sql(raw_sql)

    # 2️⃣ Execute the SQL safely
    db_path = os.path.join(os.path.dirname(__file__), "data", "mediassist.db")
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    try:
        cur = conn.execute(sql)
        rows = cur.fetchall()
        # Convert rows to list of dicts for easy JSON handling
        results: List[Dict[str, Any]] = [dict(row) for row in rows]
    finally:
        conn.close()

    # 3️⃣ Feed result back to LLM for a natural answer
    results_json = json.dumps(results, indent=2, ensure_ascii=False)
    answer_prompt = (
        f"Given the original question:\n{question}\nAnd the SQL result (JSON):\n{results_json}\nProduce a concise natural‑language answer."
    )
    answer = _call_llm(answer_prompt)
    return answer

if __name__ == "__main__":
    # Demo – replace with real credentials / role
    demo_q = "How many billing claims were escalated last month?"
    demo_role = "billing_executive"
    print(sql_rag_chain(demo_q, demo_role))
